# Generated by Django 5.1 on 2024-09-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
